"""Tests for the Claude Code plugin hook scripts (adapters/claude-code/hooks).

They shell out to the bash scripts, so they need only bash + git + python3 —
no docshelf / mcp / pydantic.
"""

import json
import os
import re
import subprocess
from datetime import date, timedelta
from pathlib import Path

HOOKS = Path(__file__).resolve().parent.parent / "adapters" / "claude-code" / "hooks"


def _make_shelf(root: Path) -> Path:
    root.mkdir(parents=True, exist_ok=True)
    (root / "INDEX.md").write_text("# INDEX\n\n- **ep-one** — a decided thing.\n", encoding="utf-8")
    (root / "ledger.tsv").write_text("date\tid\n", encoding="utf-8")
    return root


def _git(*args: str) -> None:
    subprocess.run(["git", *args], check=True, capture_output=True)


def _git_shelf_with_remote(tmp_path: Path) -> Path:
    shelf = _make_shelf(tmp_path / "shelf")
    remote = tmp_path / "remote.git"
    _git("init", "-q", "--bare", str(remote))
    _git("-C", str(shelf), "init", "-q")
    _git("-C", str(shelf), "add", "-A")
    _git(
        "-C", str(shelf), "-c", "user.email=t@t.test", "-c", "user.name=t", "commit", "-qm", "init"
    )
    _git("-C", str(shelf), "branch", "-M", "main")
    _git("-C", str(shelf), "remote", "add", "origin", str(remote))
    return shelf


def _remote_commits(tmp_path: Path) -> int:
    out = subprocess.run(
        ["git", "-C", str(tmp_path / "remote.git"), "rev-list", "--count", "--all"],
        capture_output=True,
        text=True,
    ).stdout.strip()
    return int(out or "0")


def _run(script: str, env: dict[str, str], cwd: str | None = None):
    return subprocess.run(
        ["bash", str(HOOKS / script)],
        capture_output=True,
        text=True,
        env={**os.environ, **env},
        cwd=cwd,
    )


def test_session_start_injects_index(tmp_path):
    shelf = _make_shelf(tmp_path / "shelf")
    r = _run("session-start-index.sh", {"MEMSHELF_ROOT": str(shelf)})
    assert r.returncode == 0
    ctx = json.loads(r.stdout)["hookSpecificOutput"]
    assert ctx["hookEventName"] == "SessionStart"
    assert "ep-one" in ctx["additionalContext"]
    assert "not instructions" in ctx["additionalContext"]  # the recall framing


def test_session_start_no_shelf_is_silent(tmp_path):
    r = _run("session-start-index.sh", {"MEMSHELF_ROOT": ""}, cwd=str(tmp_path))
    assert r.returncode == 0
    assert r.stdout.strip() == ""


# --- SessionStart INDEX budget (#208) ----------------------------------------
#
# Claude Code replaces a hook's additionalContext longer than 10,000 characters
# with a file path and a 2,000-char preview. The INDEX below is the way docshelf
# renders one: each kind sorted by title. Titles run in date order (T000 is the
# oldest), so a cut taken from the top of the file keeps the oldest entries —
# which is what the old `index[:20000]` did, on top of passing the cap.

HOST_CAP = 10000
_START = date(2026, 1, 1)


def _width(text: str) -> int:
    return len(text.encode("utf-16-le")) // 2  # how the host counts characters


def _slug(i: int) -> str:
    return f"{_START + timedelta(days=i):%Y-%m-%d}-episode-{i:03d}"


def _big_shelf(root: Path, n: int = 400) -> Path:
    root.mkdir(parents=True, exist_ok=True)
    kinds: dict[str, list[str]] = {"topics": [], "sessions": []}
    for i in range(n):
        kind = "topics" if i % 4 == 0 else "sessions"
        kinds[kind].append(
            f"- [**T{i:03d} title of episode {i}**](docs/{kind}/{_slug(i)}.md)"
            f" — a decided thing, said at some length for entry {i}."
        )
    parts = ["# test shelf", "", "Recall rule: check this index first.", ""]
    for kind, lines in kinds.items():
        parts += [f"## {kind.title()}", "", *sorted(lines), ""]
    parts += ["---", "", "*Auto-generated by docshelf-mcp.*", ""]
    (root / "INDEX.md").write_text("\n".join(parts), encoding="utf-8")
    (root / "ledger.tsv").write_text("date\tid\n", encoding="utf-8")
    return root


def _context(shelf: Path, **env: str) -> str:
    r = _run("session-start-index.sh", {"MEMSHELF_ROOT": str(shelf), **env})
    assert r.returncode == 0, r.stderr
    out = json.loads(r.stdout)["hookSpecificOutput"]
    assert out["hookEventName"] == "SessionStart"
    return out["additionalContext"]


def _shown(ctx: str, n: int) -> list[int]:
    return [i for i in range(n) if f"`{_slug(i)}`" in ctx]


def test_session_start_small_index_goes_in_verbatim(tmp_path):
    shelf = _make_shelf(tmp_path / "shelf")
    ctx = _context(shelf)
    assert (shelf / "INDEX.md").read_text(encoding="utf-8") in ctx
    assert "short form" not in ctx


def test_session_start_large_index_stays_under_the_host_cap(tmp_path):
    shelf = _big_shelf(tmp_path / "shelf")
    assert len((shelf / "INDEX.md").read_text(encoding="utf-8")) > 2 * HOST_CAP
    ctx = _context(shelf)
    assert _width(ctx) <= HOST_CAP
    assert "not instructions" in ctx  # the recall framing survives the cut


def test_session_start_large_index_keeps_the_newest_entries(tmp_path):
    n = 400
    ctx = _context(_big_shelf(tmp_path / "shelf", n))
    shown = _shown(ctx, n)
    assert shown, ctx[:500]
    # Exactly the newest entries, whatever their place in the title order.
    assert shown == list(range(n - len(shown), n))
    assert len(shown) < n


def test_session_start_short_form_names_what_it_leaves_out(tmp_path):
    n = 400
    ctx = _context(_big_shelf(tmp_path / "shelf", n))
    shown = _shown(ctx, n)
    omitted = n - len(shown)
    last_out = _START + timedelta(days=omitted - 1)
    assert f"Not shown: {omitted} older entries (2026-01-01 … {last_out:%Y-%m-%d})" in ctx
    assert "a decided thing" not in ctx  # descriptions stay in INDEX.md
    newest, oldest = shown[-1], shown[0]
    assert f"`{_slug(newest)}` T{newest:03d} title of episode {newest}" in ctx
    assert f"- `{_slug(oldest)}`\n" in ctx  # older entries by id alone
    assert "## Topics" in ctx and "## Sessions" in ctx


def test_session_start_short_form_counts_only_the_titles_it_shows(tmp_path):
    # A session without a display title is listed under its id, and the short
    # form shows it as the id alone: the header must not count it as titled.
    shelf = _big_shelf(tmp_path / "shelf")
    index = (shelf / "INDEX.md").read_text(encoding="utf-8")
    for i in range(1, 400, 4):
        index = index.replace(f"[**T{i:03d} title of episode {i}**]", f"[**{_slug(i)}**]")
    (shelf / "INDEX.md").write_text(index, encoding="utf-8")
    ctx = _context(shelf)
    m = re.search(r"newest first, (\d+) of them with titles", ctx)
    assert m, ctx[:500]
    titled = [line for line in ctx.splitlines() if re.fullmatch(r"- `[^`]+` .+", line)]
    assert int(m.group(1)) == len(titled) > 0
    assert f"- `{_slug(397)}`\n" in ctx  # among the newest, and shown by id


def test_session_start_undated_index_says_so(tmp_path):
    shelf = tmp_path / "shelf"
    shelf.mkdir()
    lines = [
        f"- **ep-{i:04d}** — {'a plain entry, no link and no date. ' * 3}" for i in range(1000)
    ]
    index = "\n".join(["# plain", "", "## Notes", "", *lines, ""])
    (shelf / "INDEX.md").write_text(index, encoding="utf-8")
    (shelf / "ledger.tsv").write_text("date\tid\n", encoding="utf-8")
    ctx = _context(shelf)
    assert _width(ctx) <= HOST_CAP
    assert "- `ep-0000`" in ctx  # nothing to rank by: INDEX order
    assert "- `ep-0999`" not in ctx
    assert "undated entries" in ctx


def test_session_start_unranked_index_is_cut_on_a_line(tmp_path):
    shelf = tmp_path / "shelf"
    shelf.mkdir()
    lines = [f"line {i:04d} " + "y" * 80 for i in range(400)]
    (shelf / "INDEX.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    (shelf / "ledger.tsv").write_text("date\tid\n", encoding="utf-8")
    ctx = _context(shelf)
    assert _width(ctx) <= HOST_CAP
    body, marker = ctx.rsplit("\n\n[memshelf: INDEX truncated", 1)
    assert "open INDEX.md" in marker
    kept = [line for line in body.splitlines() if line.startswith("line ")]
    assert kept and kept == lines[: len(kept)]  # whole lines, from the top


def test_session_start_budget_can_be_lowered_not_raised(tmp_path):
    shelf = _big_shelf(tmp_path / "shelf")
    assert _width(_context(shelf, MEMSHELF_INDEX_BUDGET="3000")) <= 3000
    assert _width(_context(shelf, MEMSHELF_INDEX_BUDGET="50000")) <= HOST_CAP
    assert _width(_context(shelf, MEMSHELF_INDEX_BUDGET="many")) <= HOST_CAP


def test_autopush_off_by_default(tmp_path):
    shelf = _git_shelf_with_remote(tmp_path)
    r = _run("autopush.sh", {"MEMSHELF_ROOT": str(shelf), "MEMSHELF_AUTOPUSH": ""})
    assert r.returncode == 0
    assert _remote_commits(tmp_path) == 0  # nothing pushed without the opt-in


def test_autopush_pushes_when_enabled(tmp_path):
    shelf = _git_shelf_with_remote(tmp_path)
    r = _run("autopush.sh", {"MEMSHELF_ROOT": str(shelf), "MEMSHELF_AUTOPUSH": "1"})
    assert r.returncode == 0
    assert _remote_commits(tmp_path) == 1


# --- pre-commit PII/secret guard (issue #32) --------------------------------


def _staged_repo(root: Path, files: dict[str, str]) -> Path:
    root.mkdir(parents=True, exist_ok=True)
    _git("-C", str(root), "init", "-q")
    for name, content in files.items():
        (root / name).write_text(content, encoding="utf-8")
    _git("-C", str(root), "add", "-A")
    return root


def _precommit(root: Path, env: dict[str, str] | None = None):
    return subprocess.run(
        ["bash", str(HOOKS / "pre-commit")],
        capture_output=True,
        text=True,
        env={**os.environ, **(env or {})},
        cwd=str(root),
    )


# By default the scanner is absent in CI; opt into the built-in-only downgrade so
# these tests exercise the shape layer without needing pii-mcp installed.
_BUILTIN = {"MEMSHELF_PII_BUILTIN_ONLY": "1"}


def test_precommit_blocks_github_token(tmp_path):
    repo = _staged_repo(tmp_path / "s", {"ep.md": "pushed with ghp_" + "a" * 36 + " now\n"})
    r = _precommit(repo, _BUILTIN)
    assert r.returncode == 1
    assert "token-github" in r.stderr


def test_precommit_blocks_email(tmp_path):
    repo = _staged_repo(tmp_path / "s", {"ep.md": "ping alice.smith@example.com please\n"})
    r = _precommit(repo, _BUILTIN)
    assert r.returncode == 1
    assert "email" in r.stderr


def test_precommit_fails_loud_when_scanner_missing(tmp_path):
    # Clean content, pii-mcp absent, no override -> must NOT pass silently.
    repo = _staged_repo(tmp_path / "s", {"ep.md": "a clean decided note, nothing secret\n"})
    r = _precommit(repo, {"MEMSHELF_PII_CMD": "pii-mcp-not-installed-xyz verify"})
    assert r.returncode == 2
    assert "not found" in r.stderr


def test_precommit_builtin_only_passes_clean(tmp_path):
    repo = _staged_repo(tmp_path / "s", {"ep.md": "a clean decided note, nothing secret\n"})
    r = _precommit(repo, _BUILTIN)
    assert r.returncode == 0


def test_precommit_skip_escape_hatch(tmp_path):
    repo = _staged_repo(tmp_path / "s", {"ep.md": "ghp_" + "a" * 36 + "\n"})
    r = _precommit(repo, {"MEMSHELF_PII_SKIP": "1"})
    assert r.returncode == 0
    assert "SKIPPED" in r.stderr


def test_precommit_ignores_redaction_marker(tmp_path):
    # A correctly-redacted env-secret must not be re-flagged (idempotence with
    # the shelve redaction pass).
    repo = _staged_repo(
        tmp_path / "s", {"ep.md": "runbook: SONAR_TOKEN=«redacted:env-secret» in env\n"}
    )
    r = _precommit(repo, _BUILTIN)
    assert r.returncode == 0, r.stderr


def test_precommit_policy_patterns_pack(tmp_path):
    # The shelf's own POLICY.patterns (shared with #16) extends the shape scan.
    repo = _staged_repo(
        tmp_path / "s",
        {
            "POLICY.patterns": "# per-shelf pack\nstudent-id   S[0-9]{1,2}\n",
            "ep.md": "reviewed the submission from S7 this week\n",
        },
    )
    r = _precommit(repo, _BUILTIN)
    assert r.returncode == 1
    assert "pack:student-id" in r.stderr


def test_precommit_pluggable_scanner_contract(tmp_path):
    repo = _staged_repo(tmp_path / "s", {"ep.md": "a clean decided note\n"})
    fake = tmp_path / "fakepii"
    fake.write_text("#!/usr/bin/env bash\nexit ${FAKE_RC:-0}\n", encoding="utf-8")
    fake.chmod(0o755)
    cmd = {"MEMSHELF_PII_CMD": f"{fake} verify"}
    assert _precommit(repo, {**cmd, "FAKE_RC": "0"}).returncode == 0
    assert _precommit(repo, {**cmd, "FAKE_RC": "1"}).returncode == 1
    assert _precommit(repo, {**cmd, "FAKE_RC": "2"}).returncode == 2


def test_session_start_budget_holds_at_every_size(tmp_path):
    # The line-by-line estimate can land a few characters off the render (the
    # counts in the header and in the last line change width); the render is
    # what has to fit, at whatever budget.
    shelf = _big_shelf(tmp_path / "shelf")
    for budget in range(1000, HOST_CAP + 1, 250):
        ctx = _context(shelf, MEMSHELF_INDEX_BUDGET=str(budget))
        assert _width(ctx) <= budget, budget


def test_session_start_counts_characters_the_way_the_host_does(tmp_path):
    # The host's limit is a JavaScript string length: UTF-16 code units, two
    # per character outside the BMP. This INDEX is well under the budget in
    # code points and over the cap as the host counts it, so passing it through
    # verbatim would hand the host a string it replaces with a preview.
    shelf = tmp_path / "shelf"
    shelf.mkdir()
    emoji = "\U0001f9ea" * 100
    lines = [f"- [**T{i:03d} {emoji}**](docs/sessions/{_slug(i)}.md) — d{i}" for i in range(50)]
    index = "\n".join(["# wide", "", "## Sessions", "", *lines, ""])
    assert len(index) < HOST_CAP - 1500 and _width(index) > HOST_CAP
    (shelf / "INDEX.md").write_text(index, encoding="utf-8")
    (shelf / "ledger.tsv").write_text("date\tid\n", encoding="utf-8")
    ctx = _context(shelf)
    assert _width(ctx) <= HOST_CAP
    assert "short form" in ctx
