"""Local H2 split directories: find them, and remove them (#109).

docshelf splits any document past 50 KiB into ``docs/<category>/<slug>/NNN-*.md``
next to the episode. memshelf used to let it — and then committed the episode
alone (``shelve`` stages exactly one path), so the sections never reached the
repository. The result is a shelf whose derived layer is not a function of its
committed episodes: the machine that shelved renders INDEX with a section block
the bot's checkout cannot produce, ``doctor`` reports a ``stale-index`` no
rebuild can clear, and ``search`` answers with addresses that exist on one
laptop. ``shelve`` now passes ``split=False``, so no new directory appears.

This module is the other half — the shelves that already have one. Detection is
deliberately narrow:

* only a directory sitting next to an episode of the same stem (an orphan with
  no parent document is docshelf's ``orphaned-split-dir``, a different finding);
* only on a git shelf, because "exists only in this working copy" has no meaning
  without a repository — a plain shelf renders and reads its own splits
  consistently, and nothing there diverges;
* only when git tracks nothing inside it. A shelf that *committed* its sections
  is coherent: every checkout has them. That shelf is left alone, and
  :func:`prune_split_dirs` reports it rather than deleting it.

Removal is safe by construction, not by promise: the episode file carries every
section verbatim (the split is a copy), and ``recall --section`` slices from the
episode, never from these files.
"""

from __future__ import annotations

import shutil
import subprocess
from dataclasses import dataclass, field
from pathlib import Path

from memshelf_mcp.core.archive import archive_root

#: docshelf's per-split navigation file. It lives inside the directory and goes
#: with it; it is regenerated by ``rebuild_index`` for any split that remains.
SUBINDEX_FILENAME = "SUBINDEX.md"


@dataclass
class PruneReport:
    """What :func:`prune_split_dirs` found, and what it did about it."""

    #: Untracked split directories, relative to the shelf root.
    local: list[str] = field(default_factory=list)
    #: Split directories git tracks — coherent across checkouts, left alone.
    tracked: list[str] = field(default_factory=list)
    #: What was actually deleted (empty without ``apply``).
    deleted: list[str] = field(default_factory=list)
    applied: bool = False

    def to_dict(self) -> dict:
        return {
            "status": "ok",
            "local": self.local,
            "tracked": self.tracked,
            "deleted": self.deleted,
            "count": len(self.local),
            "applied": self.applied,
            "note": (
                "the sections are a copy of the episode, which stays untouched — "
                "`recall --section` slices from the episode file itself"
            ),
        }


def _is_git(root: Path) -> bool:
    return (root / ".git").exists()


def _tracked_paths(root: Path, rel: str) -> list[str]:
    """Paths git tracks under ``rel`` — empty for an untracked directory.

    An *ignored* file is untracked, which is the point: the shelves this was
    written for ignore ``docs/*/*/`` outright.
    """
    proc = subprocess.run(
        ["git", "-C", str(root), "ls-files", "--", rel],
        capture_output=True,
        text=True,
    )
    if proc.returncode != 0:  # not a repository after all — treat as untracked
        return []
    return [line for line in proc.stdout.splitlines() if line.strip()]


def episode_split_dirs(shelf_root: str | Path) -> list[Path]:
    """Every split directory that sits next to an episode, archive included."""
    root = Path(shelf_root).expanduser().resolve()
    out: list[Path] = []
    for docs in (root / "docs", archive_root(root) / "docs"):
        if not docs.is_dir():
            continue
        for episode in sorted(docs.glob("*/*.md")):
            if episode.name == SUBINDEX_FILENAME:
                continue
            candidate = episode.with_suffix("")
            if candidate.is_dir():
                out.append(candidate)
    return out


def prune_split_dirs(shelf_root: str | Path, *, apply: bool = False) -> PruneReport:
    """Report (and with ``apply``, delete) split directories git does not track.

    Without ``apply`` nothing is written: the report is the dry run, which is
    the default because a deletion the caller did not ask for is exactly the
    class of surprise a memory tool must not produce.
    """
    root = Path(shelf_root).expanduser().resolve()
    report = PruneReport(applied=apply)
    if not _is_git(root):
        # Nothing diverges on a plain shelf: the only renderer is this one.
        return report

    for split_dir in episode_split_dirs(root):
        rel = split_dir.relative_to(root).as_posix()
        if _tracked_paths(root, rel):
            report.tracked.append(rel)
            continue
        report.local.append(rel)
        if apply:
            shutil.rmtree(split_dir)
            report.deleted.append(rel)
    return report


def local_split_dirs(shelf_root: str | Path) -> list[str]:
    """The untracked split directories, relative to the root — doctor's input."""
    return prune_split_dirs(shelf_root).local
